<?php
return [
    'BASE_URL'=> 'https://windcloud.de',
    'pwfrontsalt' =>'S_)X}()yhRWDq2M&y-F[qur_v!n).*PQ#q_9#(*.sQBFc(uA8Z',
    'pwbacksalt' =>'d=\v=a;+)#3rD=EDSucLrv&RZ8r\r$Fv8mQRmGM&wCcZkG34Z#',
    'adminEmail' => 'grote@windcloud.de',
    'contactEmail' => 'moin@windcloud.de',
    'presseEmail' => [1=>'grote@windcloud.de',2=>'green_eye@chillaz.org'],
    'produktcontactEmail' => 'support@windcloud.de',
    'produktcontactstartEmail' => 'support@windcloud.de',
    'senderEmail' => 'noreply@windcloud.de',
    'NCCustomerAssignmentEmail'=> array('grote@windcloud.de','green_eye@chillaz.org','goettling@windcloud.de','lpoghosyan@windcloud.de'),
    'senderName' => 'Example.com mailer',
    'DeleteSecret' => 'e4f5626124b0155aed8dfba2b0545064',
    'UpdateSecret' => 'e4f5626124b0155aed8dfba2b0545064',
    'RocketChatUse' => TRUE,
    'RocketChatHost' => 'https://chat.windcloud.de',
    'RocketChatUser' => 'ShopBot',
    'RocketChatPassword' => 'smRaTYpdC3DAud5S3',
    'RocketChatChannel' => 'shoplogserver',
    //'WECLAPP_BASE_URL'=> 'https://developmentwindcloud.weclapp.com',
    //'WECLAPP_API_KEY'=> 'b4a21908-b77d-4a11-bc19-79d80c9b6845',
    'WECLAPP_BASE_URL'=> 'https://ydprrrwelwcsvsy.weclapp.com',
    'WECLAPP_API_KEY'=> 'f29759a1-aece-41d9-8107-1b98a8e7489c',
    'WECLAPP_API_TICKETPRIORITY'=> 'hoch',
    'WECLAPP_API_BUCHHALTUNG_ID'=> '8628',
    'WECLAPP_API_BESTELLUNG_ID'=> '8628',
    'WECLAPP_API_CANCELLATION_MESSAGE_1'=> 'Kunde möchte sein Produkt',
    'WECLAPP_API_CANCELLATION_MESSAGE_2'=> 'zum',
    'WECLAPP_API_CANCELLATION_MESSAGE_3'=> 'Kündigung.',
    'WECLAPP_API_CANCELLATION_MESSAGE_4'=> 'Mit dem Username:',
    'WECLAPP_API_CANCELLATION_MESSAGE_5'=> 'Mit dem Server:',
    'WECLAPP_API_CANCELLATION_SUBJECT'=> 'Kündigung',
    'PROXMOXVE_HOSTNAME'=> 'devnode.proxmox.int',
    'PROXMOXVE_USERNAME'=> 'root',
    'PROXMOXVE_PASSWORD'=> 'wind#Cloud40',
    'WECLAPPIMPORT_BASE_URL'=> 'https://ydprrrwelwcsvsy.weclapp.com',
    'WECLAPPIMPORT_API_KEY'=> 'f29759a1-aece-41d9-8107-1b98a8e7489c',
    'NEXTCLOUD_API_HOSTNAME'=> 'next.windcloud.de',
    'NEXTCLOUD_API_USERNAME'=> 'shop',
    'NEXTCLOUD_API_PASSWORD'=> 'NaHzv6T8RaBrvwyx',
    'STEUERSATZ'=> 0.19,
    'STEUERSATZGANZ'=> 1.19,
    'STEUERSATZVOLL'=> 19,
    'STEUERSATZTEXT'=> '19%',
    'PayPay_BASE_URL'=> 'https://api-m.paypal.com',
    'PayPay_Client_ID'=> 'Ab0_vkQSuLSMUNRYMb5ladjKW2J0XbYJXNyPwfvY86052tlcFFTi5RDvF8PKf0ONSH1l_JLC968avVXU',
    'PayPay_Secret'=> 'EHi8z3CVYtnkNkad7NYUQMKVvfpvEyhWgm3-wCz69KFzppoH8ZQrseCoC1_G48UQomIpIn5zXUr1JF10',
    //'Sofort_Token'=> '195788:593194:e51c9641a488f2806a35a7afbb093237',
    'Sofort_Token'=> '195788:593194:d931c20c4e82385f2e8c4f637a54c546',
    //'Sofort_Token'=> '195788:705034:e51c9641a488f2806a35a7afbb093237',
];
